# permissions for end users to view replicators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replicator-viewer-role
rules:
  - apiGroups:
      - replicator.siliconhills.dev
    resources:
      - replicators
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - replicator.siliconhills.dev
    resources:
      - replicators/status
    verbs:
      - get
